<?php

declare(strict_types=1);

namespace iggyvolz\obs\Enum;

/**
 * @autogenerated
 */
enum EventSubscription: int
{
    /** Subcription value used to disable all events. */
    case None = 0;

    /** Subscription value to receive events in the `General` category. */
    case General = 1;

    /** Subscription value to receive events in the `Config` category. */
    case Config = 2;

    /** Subscription value to receive events in the `Scenes` category. */
    case Scenes = 4;

    /** Subscription value to receive events in the `Inputs` category. */
    case Inputs = 8;

    /** Subscription value to receive events in the `Transitions` category. */
    case Transitions = 16;

    /** Subscription value to receive events in the `Filters` category. */
    case Filters = 32;

    /** Subscription value to receive events in the `Outputs` category. */
    case Outputs = 64;

    /** Subscription value to receive events in the `SceneItems` category. */
    case SceneItems = 128;

    /** Subscription value to receive events in the `MediaInputs` category. */
    case MediaInputs = 256;

    /** Subscription value to receive the `VendorEvent` event. */
    case Vendors = 512;

    /** Subscription value to receive events in the `Ui` category. */
    case Ui = 1024;

    /** Subscription value to receive the `InputVolumeMeters` high-volume event. */
    case InputVolumeMeters = 65536;

    /** Subscription value to receive the `InputActiveStateChanged` high-volume event. */
    case InputActiveStateChanged = 131072;

    /** Subscription value to receive the `InputShowStateChanged` high-volume event. */
    case InputShowStateChanged = 262144;

    /** Subscription value to receive the `SceneItemTransformChanged` high-volume event. */
    case SceneItemTransformChanged = 524288;

    public const All = [
        self::General,
        self::Config,
        self::Scenes,
        self::Inputs,
        self::Transitions,
        self::Filters,
        self::Outputs,
        self::SceneItems,
        self::MediaInputs,
        self::Vendors,
    ];
}
