<?php

declare(strict_types=1);

namespace iggyvolz\obs\Enum;

/**
 * @autogenerated
 */
enum ObsMediaInputAction: string
{
    /** No action. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NONE = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NONE';

    /** Play the media input. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY';

    /** Pause the media input. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PAUSE = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PAUSE';

    /** Stop the media input. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_STOP = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_STOP';

    /** Restart the media input. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_RESTART = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_RESTART';

    /** Go to the next playlist item. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NEXT = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NEXT';

    /** Go to the previous playlist item. */
    case OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PREVIOUS = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PREVIOUS';
}
