<?php

declare(strict_types=1);

namespace iggyvolz\obs\Enum;

/**
 * @autogenerated
 */
enum RequestStatus: int
{
    /** Unknown status, should never be used. */
    case Unknown = 0;

    /** For internal use to signify a successful field check. */
    case NoError = 10;

    /** The request has succeeded. */
    case Success = 100;

    /** The `requestType` field is missing from the request data. */
    case MissingRequestType = 203;

    /** The request type is invalid or does not exist. */
    case UnknownRequestType = 204;

    /**
     * Generic error code.
     *
     * Note: A comment is required to be provided by obs-websocket.
     */
    case GenericError = 205;

    /** The request batch execution type is not supported. */
    case UnsupportedRequestBatchExecutionType = 206;

    /** A required request field is missing. */
    case MissingRequestField = 300;

    /** The request does not have a valid requestData object. */
    case MissingRequestData = 301;

    /**
     * Generic invalid request field message.
     *
     * Note: A comment is required to be provided by obs-websocket.
     */
    case InvalidRequestField = 400;

    /** A request field has the wrong data type. */
    case InvalidRequestFieldType = 401;

    /** A request field (number) is outside of the allowed range. */
    case RequestFieldOutOfRange = 402;

    /** A request field (string or array) is empty and cannot be. */
    case RequestFieldEmpty = 403;

    /** There are too many request fields (eg. a request takes two optionals, where only one is allowed at a time). */
    case TooManyRequestFields = 404;

    /** An output is running and cannot be in order to perform the request. */
    case OutputRunning = 500;

    /** An output is not running and should be. */
    case OutputNotRunning = 501;

    /** An output is paused and should not be. */
    case OutputPaused = 502;

    /** An output is not paused and should be. */
    case OutputNotPaused = 503;

    /** An output is disabled and should not be. */
    case OutputDisabled = 504;

    /** Studio mode is active and cannot be. */
    case StudioModeActive = 505;

    /** Studio mode is not active and should be. */
    case StudioModeNotActive = 506;

    /**
     * The resource was not found.
     *
     * Note: Resources are any kind of object in obs-websocket, like inputs, profiles, outputs, etc.
     */
    case ResourceNotFound = 600;

    /** The resource already exists. */
    case ResourceAlreadyExists = 601;

    /** The type of resource found is invalid. */
    case InvalidResourceType = 602;

    /** There are not enough instances of the resource in order to perform the request. */
    case NotEnoughResources = 603;

    /** The state of the resource is invalid. For example, if the resource is blocked from being accessed. */
    case InvalidResourceState = 604;

    /** The specified input (obs_source_t-OBS_SOURCE_TYPE_INPUT) had the wrong kind. */
    case InvalidInputKind = 605;

    /**
     * The resource does not support being configured.
     *
     * This is particularly relevant to transitions, where they do not always have changeable settings.
     */
    case ResourceNotConfigurable = 606;

    /** The specified filter (obs_source_t-OBS_SOURCE_TYPE_FILTER) had the wrong kind. */
    case InvalidFilterKind = 607;

    /** Creating the resource failed. */
    case ResourceCreationFailed = 700;

    /** Performing an action on the resource failed. */
    case ResourceActionFailed = 701;

    /**
     * Processing the request failed unexpectedly.
     *
     * Note: A comment is required to be provided by obs-websocket.
     */
    case RequestProcessingFailed = 702;

    /** The combination of request fields cannot be used to perform an action. */
    case CannotAct = 703;
}
