<?php

declare(strict_types=1);

namespace iggyvolz\obs\Enum;

/**
 * @autogenerated
 */
enum WebSocketOpCode: int
{
    /** The initial message sent by obs-websocket to newly connected clients. */
    case Hello = 0;

    /** The message sent by a newly connected client to obs-websocket in response to a `Hello`. */
    case Identify = 1;

    /** The response sent by obs-websocket to a client after it has successfully identified with obs-websocket. */
    case Identified = 2;

    /** The message sent by an already-identified client to update identification parameters. */
    case Reidentify = 3;

    /** The message sent by obs-websocket containing an event payload. */
    case Event = 5;

    /** The message sent by a client to obs-websocket to perform a request. */
    case Request = 6;

    /** The message sent by obs-websocket in response to a particular request from a client. */
    case RequestResponse = 7;

    /** The message sent by a client to obs-websocket to perform a batch of requests. */
    case RequestBatch = 8;

    /** The message sent by obs-websocket in response to a particular batch of requests from a client. */
    case RequestBatchResponse = 9;
}
