<?php

declare(strict_types=1);

namespace iggyvolz\obs\Enum;

/**
 * @autogenerated
 */
enum WebSocketCloseCode: int
{
    /** For internal use only to tell the request handler not to perform any close action. */
    case DontClose = 0;

    /** Unknown reason, should never be used. */
    case UnknownReason = 4000;

    /** The server was unable to decode the incoming websocket message. */
    case MessageDecodeError = 4002;

    /** A data field is required but missing from the payload. */
    case MissingDataField = 4003;

    /** A data field's value type is invalid. */
    case InvalidDataFieldType = 4004;

    /** A data field's value is invalid. */
    case InvalidDataFieldValue = 4005;

    /** The specified `op` was invalid or missing. */
    case UnknownOpCode = 4006;

    /** The client sent a websocket message without first sending `Identify` message. */
    case NotIdentified = 4007;

    /**
     * The client sent an `Identify` message while already identified.
     *
     * Note: Once a client has identified, only `Reidentify` may be used to change session parameters.
     */
    case AlreadyIdentified = 4008;

    /** The authentication attempt (via `Identify`) failed. */
    case AuthenticationFailed = 4009;

    /** The server detected the usage of an old version of the obs-websocket RPC protocol. */
    case UnsupportedRpcVersion = 4010;

    /**
     * The websocket session has been invalidated by the obs-websocket server.
     *
     * Note: This is the code used by the `Kick` button in the UI Session List. If you receive this code, you must not automatically reconnect.
     */
    case SessionInvalidated = 4011;

    /** A requested feature is not supported due to hardware/software limitations. */
    case UnsupportedFeature = 4012;
}
