<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class CallVendorRequestResponse
{
    /**
     * @param mixed $responseData
     */
    public function __construct(public readonly mixed $responseData)
    {
    }
}
