<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class CreateInputResponse
{
    /**
     * @param int $sceneItemId
     */
    public function __construct(public readonly int $sceneItemId)
    {
    }
}
