<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetCurrentSceneTransitionCursorResponse
{
    /**
     * @param int $transitionCursor
     */
    public function __construct(public readonly int $transitionCursor)
    {
    }
}
