<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetCurrentPreviewSceneResponse
{
    /**
     * @param string $currentPreviewSceneName
     */
    public function __construct(public readonly string $currentPreviewSceneName)
    {
    }
}
