<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetCurrentSceneTransitionResponse
{
    /**
     * @param string $transitionName
     * @param string $transitionKind
     * @param bool $transitionFixed
     * @param int $transitionDuration
     * @param bool $transitionConfigurable
     * @param mixed $transitionSettings
     */
    public function __construct(
        public readonly string $transitionName,
        public readonly string $transitionKind,
        public readonly bool $transitionFixed,
        public readonly int $transitionDuration,
        public readonly bool $transitionConfigurable,
        public readonly mixed $transitionSettings,
    ) {
    }
}
