<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetCurrentProgramSceneResponse
{
    /**
     * @param string $currentProgramSceneName
     */
    public function __construct(public readonly string $currentProgramSceneName)
    {
    }
}
