<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetGroupItemListResponse
{
    /**
     * @param list<mixed> $sceneItems
     */
    public function __construct(public readonly array $sceneItems)
    {
    }
}
