<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetGroupListResponse
{
    /**
     * @param list<string> $groups
     */
    public function __construct(public readonly array $groups)
    {
    }
}
