<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetHotkeyListResponse
{
    /**
     * @param list<string> $hotkeys
     */
    public function __construct(public readonly array $hotkeys)
    {
    }
}
