<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputAudioSyncOffsetResponse
{
    /**
     * @param int $inputAudioSyncOffset
     */
    public function __construct(public readonly int $inputAudioSyncOffset)
    {
    }
}
