<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputListResponse
{
    /**
     * @param list<mixed> $inputs
     */
    public function __construct(public readonly array $inputs)
    {
    }
}
