<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputMuteResponse
{
    /**
     * @param bool $inputMuted
     */
    public function __construct(public readonly bool $inputMuted)
    {
    }
}
