<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputDefaultSettingsResponse
{
    /**
     * @param mixed $defaultInputSettings
     */
    public function __construct(public readonly mixed $defaultInputSettings)
    {
    }
}
