<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputAudioMonitorTypeResponse
{
    /**
     * @param string $monitorType
     */
    public function __construct(public readonly string $monitorType)
    {
    }
}
