<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputKindListResponse
{
    /**
     * @param list<string> $inputKinds
     */
    public function __construct(public readonly array $inputKinds)
    {
    }
}
