<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputSettingsResponse
{
    /**
     * @param mixed $inputSettings
     * @param string $inputKind
     */
    public function __construct(
        public readonly mixed $inputSettings,
        public readonly string $inputKind,
    ) {
    }
}
