<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputVolumeResponse
{
    /**
     * @param int $inputVolumeMul
     * @param int $inputVolumeDb
     */
    public function __construct(
        public readonly int $inputVolumeMul,
        public readonly int $inputVolumeDb,
    ) {
    }
}
