<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputPropertiesListPropertyItemsResponse
{
    /**
     * @param list<mixed> $propertyItems
     */
    public function __construct(public readonly array $propertyItems)
    {
    }
}
