<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputAudioTracksResponse
{
    /**
     * @param mixed $inputAudioTracks
     */
    public function __construct(public readonly mixed $inputAudioTracks)
    {
    }
}
