<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetInputAudioBalanceResponse
{
    /**
     * @param int $inputAudioBalance
     */
    public function __construct(public readonly int $inputAudioBalance)
    {
    }
}
