<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetMediaInputStatusResponse
{
    /**
     * @param string $mediaState
     * @param int $mediaDuration
     * @param int $mediaCursor
     */
    public function __construct(
        public readonly string $mediaState,
        public readonly int $mediaDuration,
        public readonly int $mediaCursor,
    ) {
    }
}
