<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetProfileParameterResponse
{
    /**
     * @param string $parameterValue
     * @param string $defaultParameterValue
     */
    public function __construct(
        public readonly string $parameterValue,
        public readonly string $defaultParameterValue,
    ) {
    }
}
