<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetPersistentDataResponse
{
    /**
     * @param mixed $slotValue
     */
    public function __construct(public readonly mixed $slotValue)
    {
    }
}
