<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetProfileListResponse
{
    /**
     * @param string $currentProfileName
     * @param list<string> $profiles
     */
    public function __construct(
        public readonly string $currentProfileName,
        public readonly array $profiles,
    ) {
    }
}
