<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetRecordStatusResponse
{
    /**
     * @param bool $outputActive
     * @param bool $ouputPaused
     * @param string $outputTimecode
     * @param int $outputDuration
     * @param int $outputBytes
     */
    public function __construct(
        public readonly bool $outputActive,
        public readonly bool $ouputPaused,
        public readonly string $outputTimecode,
        public readonly int $outputDuration,
        public readonly int $outputBytes,
    ) {
    }
}
