<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetRecordDirectoryResponse
{
    /**
     * @param string $recordDirectory
     */
    public function __construct(public readonly string $recordDirectory)
    {
    }
}
