<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneCollectionListResponse
{
    /**
     * @param string $currentSceneCollectionName
     * @param list<string> $sceneCollections
     */
    public function __construct(
        public readonly string $currentSceneCollectionName,
        public readonly array $sceneCollections,
    ) {
    }
}
