<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneTransitionListResponse
{
    /**
     * @param string $currentSceneTransitionName
     * @param string $currentSceneTransitionKind
     * @param list<mixed> $transitions
     */
    public function __construct(
        public readonly string $currentSceneTransitionName,
        public readonly string $currentSceneTransitionKind,
        public readonly array $transitions,
    ) {
    }
}
