<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneItemIndexResponse
{
    /**
     * @param int $sceneItemIndex
     */
    public function __construct(public readonly int $sceneItemIndex)
    {
    }
}
