<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSourceScreenshotResponse
{
    /**
     * @param string $imageData
     */
    public function __construct(public readonly string $imageData)
    {
    }
}
