<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneItemBlendModeResponse
{
    /**
     * @param string $sceneItemBlendMode
     */
    public function __construct(public readonly string $sceneItemBlendMode)
    {
    }
}
