<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSourceFilterResponse
{
    /**
     * @param bool $filterEnabled
     * @param int $filterIndex
     * @param string $filterKind
     * @param mixed $filterSettings
     */
    public function __construct(
        public readonly bool $filterEnabled,
        public readonly int $filterIndex,
        public readonly string $filterKind,
        public readonly mixed $filterSettings,
    ) {
    }
}
