<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

use iggyvolz\obs\Requests\SceneItemTransform;

/**
 * @autogenerated
 */
class GetSceneItemTransformResponse
{
    /**
     * @param SceneItemTransform $sceneItemTransform
     */
    public function __construct(public readonly SceneItemTransform $sceneItemTransform)
    {
    }
}
