<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneListResponse
{
    /**
     * @param ?string $currentProgramSceneName
     * @param ?string $currentPreviewSceneName
     * @param list<mixed> $scenes
     */
    public function __construct(
        public readonly ?string $currentProgramSceneName,
        public readonly ?string $currentPreviewSceneName,
        public readonly array $scenes,
    ) {
    }
}
