<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSourceFilterDefaultSettingsResponse
{
    /**
     * @param mixed $defaultFilterSettings
     */
    public function __construct(public readonly mixed $defaultFilterSettings)
    {
    }
}
