<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSourceFilterListResponse
{
    /**
     * @param list<mixed> $filters
     */
    public function __construct(public readonly array $filters)
    {
    }
}
