<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneItemEnabledResponse
{
    /**
     * @param bool $sceneItemEnabled
     */
    public function __construct(public readonly bool $sceneItemEnabled)
    {
    }
}
