<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneItemTransformResponse
{
    /**
     * @param mixed $sceneItemTransform
     */
    public function __construct(public readonly mixed $sceneItemTransform)
    {
    }
}
