<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSpecialInputsResponse
{
    /**
     * @param string $desktop1
     * @param string $desktop2
     * @param string $mic1
     * @param string $mic2
     * @param string $mic3
     * @param string $mic4
     */
    public function __construct(
        public readonly string $desktop1,
        public readonly string $desktop2,
        public readonly string $mic1,
        public readonly string $mic2,
        public readonly string $mic3,
        public readonly string $mic4,
    ) {
    }
}
