<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetStreamServiceSettingsResponse
{
    /**
     * @param string $streamServiceType
     * @param mixed $streamServiceSettings
     */
    public function __construct(
        public readonly string $streamServiceType,
        public readonly mixed $streamServiceSettings,
    ) {
    }
}
