<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetSceneItemLockedResponse
{
    /**
     * @param bool $sceneItemLocked
     */
    public function __construct(public readonly bool $sceneItemLocked)
    {
    }
}
