<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetStreamStatusResponse
{
    /**
     * @param bool $outputActive
     * @param bool $outputReconnecting
     * @param string $outputTimecode
     * @param int $outputDuration
     * @param int $outputBytes
     * @param int $outputSkippedFrames
     * @param int $outputTotalFrames
     */
    public function __construct(
        public readonly bool $outputActive,
        public readonly bool $outputReconnecting,
        public readonly string $outputTimecode,
        public readonly int $outputDuration,
        public readonly int $outputBytes,
        public readonly int $outputSkippedFrames,
        public readonly int $outputTotalFrames,
    ) {
    }
}
