<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetStatsResponse
{
    /**
     * @param int $cpuUsage
     * @param int $memoryUsage
     * @param int $availableDiskSpace
     * @param int $activeFps
     * @param int $averageFrameRenderTime
     * @param int $renderSkippedFrames
     * @param int $renderTotalFrames
     * @param int $outputSkippedFrames
     * @param int $outputTotalFrames
     * @param int $webSocketSessionIncomingMessages
     * @param int $webSocketSessionOutgoingMessages
     */
    public function __construct(
        public readonly int $cpuUsage,
        public readonly int $memoryUsage,
        public readonly int $availableDiskSpace,
        public readonly int $activeFps,
        public readonly int $averageFrameRenderTime,
        public readonly int $renderSkippedFrames,
        public readonly int $renderTotalFrames,
        public readonly int $outputSkippedFrames,
        public readonly int $outputTotalFrames,
        public readonly int $webSocketSessionIncomingMessages,
        public readonly int $webSocketSessionOutgoingMessages,
    ) {
    }
}
