<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetStudioModeEnabledResponse
{
    /**
     * @param bool $studioModeEnabled
     */
    public function __construct(public readonly bool $studioModeEnabled)
    {
    }
}
