<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetTransitionKindListResponse
{
    /**
     * @param list<string> $transitionKinds
     */
    public function __construct(public readonly array $transitionKinds)
    {
    }
}
