<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetVersionResponse
{
    /**
     * @param string $obsVersion
     * @param string $obsWebSocketVersion
     * @param int $rpcVersion
     * @param list<string> $availableRequests
     * @param list<string> $supportedImageFormats
     */
    public function __construct(
        public readonly string $obsVersion,
        public readonly string $obsWebSocketVersion,
        public readonly int $rpcVersion,
        public readonly array $availableRequests,
        public readonly array $supportedImageFormats,
    ) {
    }
}
