<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class GetVideoSettingsResponse
{
    /**
     * @param int $fpsNumerator
     * @param int $fpsDenominator
     * @param int $baseWidth
     * @param int $baseHeight
     * @param int $outputWidth
     * @param int $outputHeight
     */
    public function __construct(
        public readonly int $fpsNumerator,
        public readonly int $fpsDenominator,
        public readonly int $baseWidth,
        public readonly int $baseHeight,
        public readonly int $outputWidth,
        public readonly int $outputHeight,
    ) {
    }
}
