<?php

declare(strict_types=1);

namespace iggyvolz\obs\Responses;

/**
 * @autogenerated
 */
class ToggleReplayBufferResponse
{
    /**
     * @param bool $outputActive
     */
    public function __construct(public readonly bool $outputActive)
    {
    }
}
