<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class CurrentProgramSceneChanged
{
    /**
     * @param string $sceneName
     */
    public function __construct(public readonly string $sceneName)
    {
    }
}
