<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class CurrentProfileChanged
{
    /**
     * @param string $profileName
     */
    public function __construct(public readonly string $profileName)
    {
    }
}
