<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class CurrentSceneTransitionDurationChanged
{
    /**
     * @param int $transitionDuration
     */
    public function __construct(public readonly int $transitionDuration)
    {
    }
}
