<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputAudioTracksChanged
{
    /**
     * @param string $inputName
     * @param mixed $inputAudioTracks
     */
    public function __construct(
        public readonly string $inputName,
        public readonly mixed $inputAudioTracks,
    ) {
    }
}
