<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputActiveStateChanged
{
    /**
     * @param string $inputName
     * @param bool $videoActive
     */
    public function __construct(
        public readonly string $inputName,
        public readonly bool $videoActive,
    ) {
    }
}
