<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputAudioMonitorTypeChanged
{
    /**
     * @param string $inputName
     * @param string $monitorType
     */
    public function __construct(
        public readonly string $inputName,
        public readonly string $monitorType,
    ) {
    }
}
