<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputCreated
{
    /**
     * @param string $inputName
     * @param string $inputKind
     * @param string $unversionedInputKind
     * @param mixed $inputSettings
     * @param mixed $defaultInputSettings
     */
    public function __construct(
        public readonly string $inputName,
        public readonly string $inputKind,
        public readonly string $unversionedInputKind,
        public readonly mixed $inputSettings,
        public readonly mixed $defaultInputSettings,
    ) {
    }
}
