<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputNameChanged
{
    /**
     * @param string $oldInputName
     * @param string $inputName
     */
    public function __construct(
        public readonly string $oldInputName,
        public readonly string $inputName,
    ) {
    }
}
