<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputVolumeChanged
{
    /**
     * @param string $inputName
     * @param int $inputVolumeMul
     * @param int $inputVolumeDb
     */
    public function __construct(
        public readonly string $inputName,
        public readonly int $inputVolumeMul,
        public readonly int $inputVolumeDb,
    ) {
    }
}
