<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputMuteStateChanged
{
    /**
     * @param string $inputName
     * @param bool $inputMuted
     */
    public function __construct(
        public readonly string $inputName,
        public readonly bool $inputMuted,
    ) {
    }
}
