<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class InputAudioBalanceChanged
{
    /**
     * @param string $inputName
     * @param int $inputAudioBalance
     */
    public function __construct(
        public readonly string $inputName,
        public readonly int $inputAudioBalance,
    ) {
    }
}
