<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class MediaInputPlaybackStarted
{
    /**
     * @param string $inputName
     */
    public function __construct(public readonly string $inputName)
    {
    }
}
