<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class MediaInputActionTriggered
{
    /**
     * @param string $inputName
     * @param string $mediaAction
     */
    public function __construct(
        public readonly string $inputName,
        public readonly string $mediaAction,
    ) {
    }
}
