<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class ReplayBufferSaved
{
    /**
     * @param string $savedReplayPath
     */
    public function __construct(public readonly string $savedReplayPath)
    {
    }
}
