<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneItemListReindexed
{
    /**
     * @param string $sceneName
     * @param list<mixed> $sceneItems
     */
    public function __construct(
        public readonly string $sceneName,
        public readonly array $sceneItems,
    ) {
    }
}
