<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneCreated
{
    /**
     * @param string $sceneName
     * @param bool $isGroup
     */
    public function __construct(
        public readonly string $sceneName,
        public readonly bool $isGroup,
    ) {
    }
}
