<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneItemCreated
{
    /**
     * @param string $sceneName
     * @param string $sourceName
     * @param int $sceneItemId
     * @param int $sceneItemIndex
     */
    public function __construct(
        public readonly string $sceneName,
        public readonly string $sourceName,
        public readonly int $sceneItemId,
        public readonly int $sceneItemIndex,
    ) {
    }
}
