<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneListChanged
{
    /**
     * @param list<mixed> $scenes
     */
    public function __construct(public readonly array $scenes)
    {
    }
}
