<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneNameChanged
{
    /**
     * @param string $oldSceneName
     * @param string $sceneName
     */
    public function __construct(
        public readonly string $oldSceneName,
        public readonly string $sceneName,
    ) {
    }
}
