<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneTransitionEnded
{
    /**
     * @param string $transitionName
     */
    public function __construct(public readonly string $transitionName)
    {
    }
}
