<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SceneCollectionListChanged
{
    /**
     * @param list<string> $sceneCollections
     */
    public function __construct(public readonly array $sceneCollections)
    {
    }
}
