<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SourceFilterCreated
{
    /**
     * @param string $sourceName
     * @param string $filterName
     * @param string $filterKind
     * @param int $filterIndex
     * @param mixed $filterSettings
     * @param mixed $defaultFilterSettings
     */
    public function __construct(
        public readonly string $sourceName,
        public readonly string $filterName,
        public readonly string $filterKind,
        public readonly int $filterIndex,
        public readonly mixed $filterSettings,
        public readonly mixed $defaultFilterSettings,
    ) {
    }
}
