<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SourceFilterNameChanged
{
    /**
     * @param string $sourceName
     * @param string $oldFilterName
     * @param string $filterName
     */
    public function __construct(
        public readonly string $sourceName,
        public readonly string $oldFilterName,
        public readonly string $filterName,
    ) {
    }
}
