<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class SourceFilterListReindexed
{
    /**
     * @param string $sourceName
     * @param list<mixed> $filters
     */
    public function __construct(
        public readonly string $sourceName,
        public readonly array $filters,
    ) {
    }
}
