<?php

declare(strict_types=1);

namespace iggyvolz\obs\Event;

/**
 * @autogenerated
 */
class VendorEvent
{
    /**
     * @param string $vendorName
     * @param string $eventType
     * @param mixed $eventData
     */
    public function __construct(
        public readonly string $vendorName,
        public readonly string $eventType,
        public readonly mixed $eventData,
    ) {
    }
}
