<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CallVendorRequest
{
    /**
     * @param string $vendorName Name of the vendor to use
     * @param string $requestType The request type to call
     * @param mixed $requestData Object containing appropriate request data
     * @return \Amp\Future<\iggyvolz\obs\Responses\CallVendorRequestResponse>
     */
    public function callVendorRequest(string $vendorName, string $requestType, mixed $requestData): \Amp\Future
    {
        return $this->request([
            "vendorName" => $vendorName,
            "requestType" => $requestType,
            "requestData" => $requestData,
        ], "CallVendorRequest", \iggyvolz\obs\Responses\CallVendorRequestResponse::class);
    }
}
