<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CreateProfile
{
    /**
     * @param string $profileName Name for the new profile
     * @return \Amp\Future<void>
     */
    public function createProfile(string $profileName): \Amp\Future
    {
        return $this->request([
            "profileName" => $profileName,
        ], "CreateProfile");
    }
}
