<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CreateScene
{
    /**
     * @param string $sceneName Name for the new scene
     * @return \Amp\Future<void>
     */
    public function createScene(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "CreateScene");
    }
}
