<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CreateInput
{
    /**
     * @param string $sceneName Name of the scene to add the input to as a scene item
     * @param string $inputName Name of the new input to created
     * @param string $inputKind The kind of input to be created
     * @param mixed $inputSettings Settings object to initialize the input with
     * @param null|bool $sceneItemEnabled Whether to set the created scene item to enabled or disabled
     * @return \Amp\Future<\iggyvolz\obs\Responses\CreateInputResponse>
     */
    public function createInput(
        string $sceneName,
        string $inputName,
        string $inputKind,
        mixed $inputSettings,
        null|bool $sceneItemEnabled = null
    ): \Amp\Future {
        return $this->request([
            "sceneName" => $sceneName,
            "inputName" => $inputName,
            "inputKind" => $inputKind,
            "inputSettings" => $inputSettings,
            "sceneItemEnabled" => $sceneItemEnabled,
        ], "CreateInput", \iggyvolz\obs\Responses\CreateInputResponse::class);
    }
}
