<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CreateSourceFilter
{
    /**
     * @param string $sourceName Name of the source to add the filter to
     * @param string $filterName Name of the new filter to be created
     * @param string $filterKind The kind of filter to be created
     * @param mixed $filterSettings Settings object to initialize the filter with
     * @return \Amp\Future<void>
     */
    public function createSourceFilter(
        string $sourceName,
        string $filterName,
        string $filterKind,
        mixed $filterSettings
    ): \Amp\Future {
        return $this->request([
            "sourceName" => $sourceName,
            "filterName" => $filterName,
            "filterKind" => $filterKind,
            "filterSettings" => $filterSettings,
        ], "CreateSourceFilter");
    }
}
