<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait CreateSceneItem
{
    /**
     * @param string $sceneName Name of the scene to create the new item in
     * @param string $sourceName Name of the source to add to the scene
     * @param null|bool $sceneItemEnabled Enable state to apply to the scene item on creation
     * @return \Amp\Future<\iggyvolz\obs\Responses\CreateSceneItemResponse>
     */
    public function createSceneItem(
        string $sceneName,
        string $sourceName,
        null|bool $sceneItemEnabled = null
    ): \Amp\Future {
        return $this->request([
            "sceneName" => $sceneName,
            "sourceName" => $sourceName,
            "sceneItemEnabled" => $sceneItemEnabled,
        ], "CreateSceneItem", \iggyvolz\obs\Responses\CreateSceneItemResponse::class);
    }
}
