<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetCurrentSceneTransitionCursor
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetCurrentSceneTransitionCursorResponse>
     */
    public function getCurrentSceneTransitionCursor(): \Amp\Future
    {
        return $this->request([
        ], "GetCurrentSceneTransitionCursor", \iggyvolz\obs\Responses\GetCurrentSceneTransitionCursorResponse::class);
    }
}
