<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetCurrentSceneTransition
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetCurrentSceneTransitionResponse>
     */
    public function getCurrentSceneTransition(): \Amp\Future
    {
        return $this->request([
        ], "GetCurrentSceneTransition", \iggyvolz\obs\Responses\GetCurrentSceneTransitionResponse::class);
    }
}
