<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetCurrentPreviewScene
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetCurrentPreviewSceneResponse>
     */
    public function getCurrentPreviewScene(): \Amp\Future
    {
        return $this->request([
        ], "GetCurrentPreviewScene", \iggyvolz\obs\Responses\GetCurrentPreviewSceneResponse::class);
    }
}
