<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetGroupItemList
{
    /**
     * @param string $sceneName Name of the group to get the items of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetGroupItemListResponse>
     */
    public function getGroupItemList(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "GetGroupItemList", \iggyvolz\obs\Responses\GetGroupItemListResponse::class);
    }
}
