<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputAudioBalance
{
    /**
     * @param string $inputName Name of the input to get the audio balance of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputAudioBalanceResponse>
     */
    public function getInputAudioBalance(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetInputAudioBalance", \iggyvolz\obs\Responses\GetInputAudioBalanceResponse::class);
    }
}
