<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputSettings
{
    /**
     * @param string $inputName Name of the input to get the settings of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputSettingsResponse>
     */
    public function getInputSettings(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetInputSettings", \iggyvolz\obs\Responses\GetInputSettingsResponse::class);
    }
}
