<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputAudioTracks
{
    /**
     * @param string $inputName Name of the input
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputAudioTracksResponse>
     */
    public function getInputAudioTracks(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetInputAudioTracks", \iggyvolz\obs\Responses\GetInputAudioTracksResponse::class);
    }
}
