<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputKindList
{
    /**
     * @param null|bool $unversioned True == Return all kinds as unversioned, False == Return with version suffixes (if available)
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputKindListResponse>
     */
    public function getInputKindList(null|bool $unversioned = null): \Amp\Future
    {
        return $this->request([
            "unversioned" => $unversioned,
        ], "GetInputKindList", \iggyvolz\obs\Responses\GetInputKindListResponse::class);
    }
}
