<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputMute
{
    /**
     * @param string $inputName Name of input to get the mute state of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputMuteResponse>
     */
    public function getInputMute(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetInputMute", \iggyvolz\obs\Responses\GetInputMuteResponse::class);
    }
}
