<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputAudioMonitorType
{
    /**
     * @param string $inputName Name of the input to get the audio monitor type of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputAudioMonitorTypeResponse>
     */
    public function getInputAudioMonitorType(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetInputAudioMonitorType", \iggyvolz\obs\Responses\GetInputAudioMonitorTypeResponse::class);
    }
}
