<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputDefaultSettings
{
    /**
     * @param string $inputKind Input kind to get the default settings for
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputDefaultSettingsResponse>
     */
    public function getInputDefaultSettings(string $inputKind): \Amp\Future
    {
        return $this->request([
            "inputKind" => $inputKind,
        ], "GetInputDefaultSettings", \iggyvolz\obs\Responses\GetInputDefaultSettingsResponse::class);
    }
}
