<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetInputPropertiesListPropertyItems
{
    /**
     * @param string $inputName Name of the input
     * @param string $propertyName Name of the list property to get the items of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetInputPropertiesListPropertyItemsResponse>
     */
    public function getInputPropertiesListPropertyItems(string $inputName, string $propertyName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "propertyName" => $propertyName,
        ], "GetInputPropertiesListPropertyItems", \iggyvolz\obs\Responses\GetInputPropertiesListPropertyItemsResponse::class);
    }
}
