<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetLastReplayBufferReplay
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetLastReplayBufferReplayResponse>
     */
    public function getLastReplayBufferReplay(): \Amp\Future
    {
        return $this->request([
        ], "GetLastReplayBufferReplay", \iggyvolz\obs\Responses\GetLastReplayBufferReplayResponse::class);
    }
}
