<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetMediaInputStatus
{
    /**
     * @param string $inputName Name of the media input
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetMediaInputStatusResponse>
     */
    public function getMediaInputStatus(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "GetMediaInputStatus", \iggyvolz\obs\Responses\GetMediaInputStatusResponse::class);
    }
}
