<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetProfileList
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetProfileListResponse>
     */
    public function getProfileList(): \Amp\Future
    {
        return $this->request([
        ], "GetProfileList", \iggyvolz\obs\Responses\GetProfileListResponse::class);
    }
}
