<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetRecordStatus
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetRecordStatusResponse>
     */
    public function getRecordStatus(): \Amp\Future
    {
        return $this->request([
        ], "GetRecordStatus", \iggyvolz\obs\Responses\GetRecordStatusResponse::class);
    }
}
