<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneTransitionList
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneTransitionListResponse>
     */
    public function getSceneTransitionList(): \Amp\Future
    {
        return $this->request([
        ], "GetSceneTransitionList", \iggyvolz\obs\Responses\GetSceneTransitionListResponse::class);
    }
}
