<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneCollectionList
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneCollectionListResponse>
     */
    public function getSceneCollectionList(): \Amp\Future
    {
        return $this->request([
        ], "GetSceneCollectionList", \iggyvolz\obs\Responses\GetSceneCollectionListResponse::class);
    }
}
