<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetStats
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetStatsResponse>
     */
    public function getStats(): \Amp\Future
    {
        return $this->request([
        ], "GetStats", \iggyvolz\obs\Responses\GetStatsResponse::class);
    }
}
