<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSourceFilter
{
    /**
     * @param string $sourceName Name of the source
     * @param string $filterName Name of the filter
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSourceFilterResponse>
     */
    public function getSourceFilter(string $sourceName, string $filterName): \Amp\Future
    {
        return $this->request([
            "sourceName" => $sourceName,
            "filterName" => $filterName,
        ], "GetSourceFilter", \iggyvolz\obs\Responses\GetSourceFilterResponse::class);
    }
}
