<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneItemId
{
    /**
     * @param string $sceneName Name of the scene or group to search in
     * @param string $sourceName Name of the source to find
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneItemIdResponse>
     */
    public function getSceneItemId(string $sceneName, string $sourceName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sourceName" => $sourceName,
        ], "GetSceneItemId", \iggyvolz\obs\Responses\GetSceneItemIdResponse::class);
    }
}
