<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneItemList
{
    /**
     * @param string $sceneName Name of the scene to get the items of
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneItemListResponse>
     */
    public function getSceneItemList(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "GetSceneItemList", \iggyvolz\obs\Responses\GetSceneItemListResponse::class);
    }
}
