<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetStreamStatus
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetStreamStatusResponse>
     */
    public function getStreamStatus(): \Amp\Future
    {
        return $this->request([
        ], "GetStreamStatus", \iggyvolz\obs\Responses\GetStreamStatusResponse::class);
    }
}
