<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSourceFilterList
{
    /**
     * @param string $sourceName Name of the source
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSourceFilterListResponse>
     */
    public function getSourceFilterList(string $sourceName): \Amp\Future
    {
        return $this->request([
            "sourceName" => $sourceName,
        ], "GetSourceFilterList", \iggyvolz\obs\Responses\GetSourceFilterListResponse::class);
    }
}
