<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetStudioModeEnabled
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetStudioModeEnabledResponse>
     */
    public function getStudioModeEnabled(): \Amp\Future
    {
        return $this->request([
        ], "GetStudioModeEnabled", \iggyvolz\obs\Responses\GetStudioModeEnabledResponse::class);
    }
}
