<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetStreamServiceSettings
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetStreamServiceSettingsResponse>
     */
    public function getStreamServiceSettings(): \Amp\Future
    {
        return $this->request([
        ], "GetStreamServiceSettings", \iggyvolz\obs\Responses\GetStreamServiceSettingsResponse::class);
    }
}
