<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneItemEnabled
{
    /**
     * @param string $sceneName Name of the scene the item is in
     * @param int $sceneItemId Numeric ID of the scene item
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneItemEnabledResponse>
     */
    public function getSceneItemEnabled(string $sceneName, int $sceneItemId): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sceneItemId" => $sceneItemId,
        ], "GetSceneItemEnabled", \iggyvolz\obs\Responses\GetSceneItemEnabledResponse::class);
    }
}
