<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetSceneSceneTransitionOverride
{
    /**
     * @param string $sceneName Name of the scene
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetSceneSceneTransitionOverrideResponse>
     */
    public function getSceneSceneTransitionOverride(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "GetSceneSceneTransitionOverride", \iggyvolz\obs\Responses\GetSceneSceneTransitionOverrideResponse::class);
    }
}
