<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetVersion
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetVersionResponse>
     */
    public function getVersion(): \Amp\Future
    {
        return $this->request([
        ], "GetVersion", \iggyvolz\obs\Responses\GetVersionResponse::class);
    }
}
