<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetVirtualCamStatus
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetVirtualCamStatusResponse>
     */
    public function getVirtualCamStatus(): \Amp\Future
    {
        return $this->request([
        ], "GetVirtualCamStatus", \iggyvolz\obs\Responses\GetVirtualCamStatusResponse::class);
    }
}
