<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait GetVideoSettings
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\GetVideoSettingsResponse>
     */
    public function getVideoSettings(): \Amp\Future
    {
        return $this->request([
        ], "GetVideoSettings", \iggyvolz\obs\Responses\GetVideoSettingsResponse::class);
    }
}
