<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait OffsetMediaInputCursor
{
    /**
     * @param string $inputName Name of the media input
     * @param int $mediaCursorOffset Value to offset the current cursor position by
     * @return \Amp\Future<void>
     */
    public function offsetMediaInputCursor(string $inputName, int $mediaCursorOffset): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "mediaCursorOffset" => $mediaCursorOffset,
        ], "OffsetMediaInputCursor");
    }
}
