<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait PauseRecord
{
    /**
     * @return \Amp\Future<void>
     */
    public function pauseRecord(): \Amp\Future
    {
        return $this->request([
        ], "PauseRecord");
    }
}
