<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait RemoveSourceFilter
{
    /**
     * @param string $sourceName Name of the source the filter is on
     * @param string $filterName Name of the filter to remove
     * @return \Amp\Future<void>
     */
    public function removeSourceFilter(string $sourceName, string $filterName): \Amp\Future
    {
        return $this->request([
            "sourceName" => $sourceName,
            "filterName" => $filterName,
        ], "RemoveSourceFilter");
    }
}
