<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait RemoveScene
{
    /**
     * @param string $sceneName Name of the scene to remove
     * @return \Amp\Future<void>
     */
    public function removeScene(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "RemoveScene");
    }
}
