<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait RemoveSceneItem
{
    /**
     * @param string $sceneName Name of the scene the item is in
     * @param int $sceneItemId Numeric ID of the scene item
     * @return \Amp\Future<void>
     */
    public function removeSceneItem(string $sceneName, int $sceneItemId): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sceneItemId" => $sceneItemId,
        ], "RemoveSceneItem");
    }
}
