<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait RemoveInput
{
    /**
     * @param string $inputName Name of the input to remove
     * @return \Amp\Future<void>
     */
    public function removeInput(string $inputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
        ], "RemoveInput");
    }
}
