<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SaveReplayBuffer
{
    /**
     * @return \Amp\Future<void>
     */
    public function saveReplayBuffer(): \Amp\Future
    {
        return $this->request([
        ], "SaveReplayBuffer");
    }
}
