<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentSceneCollection
{
    /**
     * @param string $sceneCollectionName Name of the scene collection to switch to
     * @return \Amp\Future<void>
     */
    public function setCurrentSceneCollection(string $sceneCollectionName): \Amp\Future
    {
        return $this->request([
            "sceneCollectionName" => $sceneCollectionName,
        ], "SetCurrentSceneCollection");
    }
}
