<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentProfile
{
    /**
     * @param string $profileName Name of the profile to switch to
     * @return \Amp\Future<void>
     */
    public function setCurrentProfile(string $profileName): \Amp\Future
    {
        return $this->request([
            "profileName" => $profileName,
        ], "SetCurrentProfile");
    }
}
