<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentPreviewScene
{
    /**
     * @param string $sceneName Scene to set as the current preview scene
     * @return \Amp\Future<void>
     */
    public function setCurrentPreviewScene(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "SetCurrentPreviewScene");
    }
}
