<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentSceneTransitionDuration
{
    /**
     * @param int $transitionDuration Duration in milliseconds
     * @return \Amp\Future<void>
     */
    public function setCurrentSceneTransitionDuration(int $transitionDuration): \Amp\Future
    {
        return $this->request([
            "transitionDuration" => $transitionDuration,
        ], "SetCurrentSceneTransitionDuration");
    }
}
