<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentSceneTransitionSettings
{
    /**
     * @param mixed $transitionSettings Settings object to apply to the transition. Can be `{}`
     * @param null|bool $overlay Whether to overlay over the current settings or replace them
     * @return \Amp\Future<void>
     */
    public function setCurrentSceneTransitionSettings(mixed $transitionSettings, null|bool $overlay = null): \Amp\Future
    {
        return $this->request([
            "transitionSettings" => $transitionSettings,
            "overlay" => $overlay,
        ], "SetCurrentSceneTransitionSettings");
    }
}
