<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetCurrentProgramScene
{
    /**
     * @param string $sceneName Scene to set as the current program scene
     * @return \Amp\Future<void>
     */
    public function setCurrentProgramScene(string $sceneName): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
        ], "SetCurrentProgramScene");
    }
}
