<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputAudioSyncOffset
{
    /**
     * @param string $inputName Name of the input to set the audio sync offset of
     * @param int $inputAudioSyncOffset New audio sync offset in milliseconds
     * @return \Amp\Future<void>
     */
    public function setInputAudioSyncOffset(string $inputName, int $inputAudioSyncOffset): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "inputAudioSyncOffset" => $inputAudioSyncOffset,
        ], "SetInputAudioSyncOffset");
    }
}
