<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputMute
{
    /**
     * @param string $inputName Name of the input to set the mute state of
     * @param bool $inputMuted Whether to mute the input or not
     * @return \Amp\Future<void>
     */
    public function setInputMute(string $inputName, bool $inputMuted): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "inputMuted" => $inputMuted,
        ], "SetInputMute");
    }
}
