<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputVolume
{
    /**
     * @param string $inputName Name of the input to set the volume of
     * @param null|int $inputVolumeMul Volume setting in mul
     * @param null|int $inputVolumeDb Volume setting in dB
     * @return \Amp\Future<void>
     */
    public function setInputVolume(
        string $inputName,
        null|int $inputVolumeMul = null,
        null|int $inputVolumeDb = null
    ): \Amp\Future {
        return $this->request([
            "inputName" => $inputName,
            "inputVolumeMul" => $inputVolumeMul,
            "inputVolumeDb" => $inputVolumeDb,
        ], "SetInputVolume");
    }
}
