<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputAudioTracks
{
    /**
     * @param string $inputName Name of the input
     * @param mixed $inputAudioTracks Track settings to apply
     * @return \Amp\Future<void>
     */
    public function setInputAudioTracks(string $inputName, mixed $inputAudioTracks): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "inputAudioTracks" => $inputAudioTracks,
        ], "SetInputAudioTracks");
    }
}
