<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputAudioMonitorType
{
    /**
     * @param string $inputName Name of the input to set the audio monitor type of
     * @param string $monitorType Audio monitor type
     * @return \Amp\Future<void>
     */
    public function setInputAudioMonitorType(string $inputName, string $monitorType): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "monitorType" => $monitorType,
        ], "SetInputAudioMonitorType");
    }
}
