<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputName
{
    /**
     * @param string $inputName Current input name
     * @param string $newInputName New name for the input
     * @return \Amp\Future<void>
     */
    public function setInputName(string $inputName, string $newInputName): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "newInputName" => $newInputName,
        ], "SetInputName");
    }
}
