<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetInputSettings
{
    /**
     * @param string $inputName Name of the input to set the settings of
     * @param mixed $inputSettings Object of settings to apply
     * @param null|bool $overlay True == apply the settings on top of existing ones, False == reset the input to its defaults, then apply settings.
     * @return \Amp\Future<void>
     */
    public function setInputSettings(string $inputName, mixed $inputSettings, null|bool $overlay = null): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "inputSettings" => $inputSettings,
            "overlay" => $overlay,
        ], "SetInputSettings");
    }
}
