<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetMediaInputCursor
{
    /**
     * @param string $inputName Name of the media input
     * @param int $mediaCursor New cursor position to set
     * @return \Amp\Future<void>
     */
    public function setMediaInputCursor(string $inputName, int $mediaCursor): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "mediaCursor" => $mediaCursor,
        ], "SetMediaInputCursor");
    }
}
