<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetProfileParameter
{
    /**
     * @param string $parameterCategory Category of the parameter to set
     * @param string $parameterName Name of the parameter to set
     * @param string $parameterValue Value of the parameter to set. Use `null` to delete
     * @return \Amp\Future<void>
     */
    public function setProfileParameter(
        string $parameterCategory,
        string $parameterName,
        string $parameterValue
    ): \Amp\Future {
        return $this->request([
            "parameterCategory" => $parameterCategory,
            "parameterName" => $parameterName,
            "parameterValue" => $parameterValue,
        ], "SetProfileParameter");
    }
}
