<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetPersistentData
{
    /**
     * @param string $realm The data realm to select. `OBS_WEBSOCKET_DATA_REALM_GLOBAL` or `OBS_WEBSOCKET_DATA_REALM_PROFILE`
     * @param string $slotName The name of the slot to retrieve data from
     * @param mixed $slotValue The value to apply to the slot
     * @return \Amp\Future<void>
     */
    public function setPersistentData(string $realm, string $slotName, mixed $slotValue): \Amp\Future
    {
        return $this->request([
            "realm" => $realm,
            "slotName" => $slotName,
            "slotValue" => $slotValue,
        ], "SetPersistentData");
    }
}
