<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetSourceFilterSettings
{
    /**
     * @param string $sourceName Name of the source the filter is on
     * @param string $filterName Name of the filter to set the settings of
     * @param mixed $filterSettings Object of settings to apply
     * @param null|bool $overlay True == apply the settings on top of existing ones, False == reset the input to its defaults, then apply settings.
     * @return \Amp\Future<void>
     */
    public function setSourceFilterSettings(
        string $sourceName,
        string $filterName,
        mixed $filterSettings,
        null|bool $overlay = null
    ): \Amp\Future {
        return $this->request([
            "sourceName" => $sourceName,
            "filterName" => $filterName,
            "filterSettings" => $filterSettings,
            "overlay" => $overlay,
        ], "SetSourceFilterSettings");
    }
}
