<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetSceneItemIndex
{
    /**
     * @param string $sceneName Name of the scene the item is in
     * @param int $sceneItemId Numeric ID of the scene item
     * @param int $sceneItemIndex New index position of the scene item
     * @return \Amp\Future<void>
     */
    public function setSceneItemIndex(string $sceneName, int $sceneItemId, int $sceneItemIndex): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sceneItemId" => $sceneItemId,
            "sceneItemIndex" => $sceneItemIndex,
        ], "SetSceneItemIndex");
    }
}
