<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetSceneItemLocked
{
    /**
     * @param string $sceneName Name of the scene the item is in
     * @param int $sceneItemId Numeric ID of the scene item
     * @param bool $sceneItemLocked New lock state of the scene item
     * @return \Amp\Future<void>
     */
    public function setSceneItemLocked(string $sceneName, int $sceneItemId, bool $sceneItemLocked): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sceneItemId" => $sceneItemId,
            "sceneItemLocked" => $sceneItemLocked,
        ], "SetSceneItemLocked");
    }
}
