<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetSceneItemBlendMode
{
    /**
     * @param string $sceneName Name of the scene the item is in
     * @param int $sceneItemId Numeric ID of the scene item
     * @param string $sceneItemBlendMode New blend mode
     * @return \Amp\Future<void>
     */
    public function setSceneItemBlendMode(string $sceneName, int $sceneItemId, string $sceneItemBlendMode): \Amp\Future
    {
        return $this->request([
            "sceneName" => $sceneName,
            "sceneItemId" => $sceneItemId,
            "sceneItemBlendMode" => $sceneItemBlendMode,
        ], "SetSceneItemBlendMode");
    }
}
