<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetStreamServiceSettings
{
    /**
     * @param string $streamServiceType Type of stream service to apply. Example: `rtmp_common` or `rtmp_custom`
     * @param mixed $streamServiceSettings Settings to apply to the service
     * @return \Amp\Future<void>
     */
    public function setStreamServiceSettings(string $streamServiceType, mixed $streamServiceSettings): \Amp\Future
    {
        return $this->request([
            "streamServiceType" => $streamServiceType,
            "streamServiceSettings" => $streamServiceSettings,
        ], "SetStreamServiceSettings");
    }
}
