<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetStudioModeEnabled
{
    /**
     * @param bool $studioModeEnabled True == Enabled, False == Disabled
     * @return \Amp\Future<void>
     */
    public function setStudioModeEnabled(bool $studioModeEnabled): \Amp\Future
    {
        return $this->request([
            "studioModeEnabled" => $studioModeEnabled,
        ], "SetStudioModeEnabled");
    }
}
