<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetSourceFilterName
{
    /**
     * @param string $sourceName Name of the source the filter is on
     * @param string $filterName Current name of the filter
     * @param string $newFilterName New name for the filter
     * @return \Amp\Future<void>
     */
    public function setSourceFilterName(string $sourceName, string $filterName, string $newFilterName): \Amp\Future
    {
        return $this->request([
            "sourceName" => $sourceName,
            "filterName" => $filterName,
            "newFilterName" => $newFilterName,
        ], "SetSourceFilterName");
    }
}
