<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait SetVideoSettings
{
    /**
     * @param null|int $fpsNumerator Numerator of the fractional FPS value
     * @param null|int $fpsDenominator Denominator of the fractional FPS value
     * @param null|int $baseWidth Width of the base (canvas) resolution in pixels
     * @param null|int $baseHeight Height of the base (canvas) resolution in pixels
     * @param null|int $outputWidth Width of the output resolution in pixels
     * @param null|int $outputHeight Height of the output resolution in pixels
     * @return \Amp\Future<void>
     */
    public function setVideoSettings(
        null|int $fpsNumerator = null,
        null|int $fpsDenominator = null,
        null|int $baseWidth = null,
        null|int $baseHeight = null,
        null|int $outputWidth = null,
        null|int $outputHeight = null
    ): \Amp\Future {
        return $this->request([
            "fpsNumerator" => $fpsNumerator,
            "fpsDenominator" => $fpsDenominator,
            "baseWidth" => $baseWidth,
            "baseHeight" => $baseHeight,
            "outputWidth" => $outputWidth,
            "outputHeight" => $outputHeight,
        ], "SetVideoSettings");
    }
}
