<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait Sleep
{
    /**
     * @param int $sleepMillis Number of milliseconds to sleep for (if `SERIAL_REALTIME` mode)
     * @param int $sleepFrames Number of frames to sleep for (if `SERIAL_FRAME` mode)
     * @return \Amp\Future<void>
     */
    public function sleep(int $sleepMillis, int $sleepFrames): \Amp\Future
    {
        return $this->request([
            "sleepMillis" => $sleepMillis,
            "sleepFrames" => $sleepFrames,
        ], "Sleep");
    }
}
