<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait StartVirtualCam
{
    /**
     * @return \Amp\Future<void>
     */
    public function startVirtualCam(): \Amp\Future
    {
        return $this->request([
        ], "StartVirtualCam");
    }
}
