<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait StartReplayBuffer
{
    /**
     * @return \Amp\Future<void>
     */
    public function startReplayBuffer(): \Amp\Future
    {
        return $this->request([
        ], "StartReplayBuffer");
    }
}
