<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait StopRecord
{
    /**
     * @return \Amp\Future<void>
     */
    public function stopRecord(): \Amp\Future
    {
        return $this->request([
        ], "StopRecord");
    }
}
