<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait StopVirtualCam
{
    /**
     * @return \Amp\Future<void>
     */
    public function stopVirtualCam(): \Amp\Future
    {
        return $this->request([
        ], "StopVirtualCam");
    }
}
