<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait StopReplayBuffer
{
    /**
     * @return \Amp\Future<void>
     */
    public function stopReplayBuffer(): \Amp\Future
    {
        return $this->request([
        ], "StopReplayBuffer");
    }
}
