<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait ToggleRecord
{
    /**
     * @return \Amp\Future<void>
     */
    public function toggleRecord(): \Amp\Future
    {
        return $this->request([
        ], "ToggleRecord");
    }
}
