<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait ToggleStream
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\ToggleStreamResponse>
     */
    public function toggleStream(): \Amp\Future
    {
        return $this->request([
        ], "ToggleStream", \iggyvolz\obs\Responses\ToggleStreamResponse::class);
    }
}
