<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait ToggleVirtualCam
{
    /**
     * @return \Amp\Future<\iggyvolz\obs\Responses\ToggleVirtualCamResponse>
     */
    public function toggleVirtualCam(): \Amp\Future
    {
        return $this->request([
        ], "ToggleVirtualCam", \iggyvolz\obs\Responses\ToggleVirtualCamResponse::class);
    }
}
