<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait TriggerStudioModeTransition
{
    /**
     * @return \Amp\Future<void>
     */
    public function triggerStudioModeTransition(): \Amp\Future
    {
        return $this->request([
        ], "TriggerStudioModeTransition");
    }
}
