<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait TriggerMediaInputAction
{
    /**
     * @param string $inputName Name of the media input
     * @param string $mediaAction Identifier of the `ObsMediaInputAction` enum
     * @return \Amp\Future<void>
     */
    public function triggerMediaInputAction(string $inputName, string $mediaAction): \Amp\Future
    {
        return $this->request([
            "inputName" => $inputName,
            "mediaAction" => $mediaAction,
        ], "TriggerMediaInputAction");
    }
}
