<?php

declare(strict_types=1);

namespace iggyvolz\obs\Requests;

/**
 * @autogenerated
 */
trait TriggerHotkeyByKeySequence
{
    /**
     * @param null|string $keyId The OBS key ID to use. See https://github.com/obsproject/obs-studio/blob/master/libobs/obs-hotkeys.h
     * @param mixed $keyModifiers Object containing key modifiers to apply
     * @return \Amp\Future<void>
     */
    public function triggerHotkeyByKeySequence(null|string $keyId = null, mixed $keyModifiers): \Amp\Future
    {
        return $this->request([
            "keyId" => $keyId,
            "keyModifiers" => $keyModifiers,
            "keyModifiers.shift" => $keyModifiers.shift,
            "keyModifiers.control" => $keyModifiers.control,
            "keyModifiers.alt" => $keyModifiers.alt,
            "keyModifiers.command" => $keyModifiers.command,
        ], "TriggerHotkeyByKeySequence");
    }
}
